name: kpop_info
description: flutter app that you can get information about kpop groups
publish_to: 'none'

version: 1.1.0+3

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.4.3
  firebase_core: ^2.7.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.2
  infinite_scroll_pagination: ^3.2.0
  retrofit: ^4.0.1
  dio: ^5.0.2
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.4
  build_runner:
  flutter_launcher_icons: ^0.12.0
  rename: ^2.1.1
  flutter_native_splash: ^2.2.19
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1
  dartz: ^0.10.1

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/launcher_icon.png