name: kpop_info
description: flutter app that you can get information about kpop groups
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cloud_firestore: ^4.4.3
  firebase_core: ^2.7.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.4
  build_runner:

flutter:
  uses-material-design: true